// ARRAYS DE PALABRAS
// LA PRIMERA ES EL NOMBRE DE LA CATEGORIA - NO SE SORTEA
var palabrasUsuario = ["Palabras de Usuario"];
var masLargas = ["Palabras más largas", "electroencefalografista", "esternocleidomastoideo", "electroencefalografico", "anticonstitucionalidad", "constitucionalizacion", "contrarrevolucionario", "corresponsabilizacion", "desproporcionadamente", "electroencefalografia", "interdisciplinariedad", "preterintencionalidad", "pseudohermafroditismo", "circunferencialmente", "circunstanciadamente", "correspondientemente", "desacostumbradamente", "desindustrializacion", "extraterritorialidad", "hipercaracterizacion", "incomprehensibilidad", "inconstitucionalidad", "interdisciplinaridad", "internacionalizacion"];
var paises = ["Paises del Mundo", "Australia", "Austria", "Azerbaiyan", "Bahamas", "Bahrein", "Bangladesh", "Barbados", "Belarus", "Belgica", "Belice", "Benin", "Bhutan", "Bolivia", "BosniayHerzegovina", "Botswana", "Brasil", "Brunei", "Bulgaria", "BurkinaFaso", "Burundi", "CaboVerde", "Camboya", "Camerun", "Canada", "Chad", "Chequia", "Chile", "China", "Chipre", "Colombia", "Congo", "", "", "Croacia", "Cuba", "Dinamarca", "Djibouti", "Dominica", "Ecuador", "Egipto", "ElSalvador", "EmiratosarabesUnidos", "Eritrea", "Eslovaquia", "Eslovenia", "España", "EstadosUnidosdeAmerica", "Estonia", "Eswatini", "Etiopia", "FederaciondeRusia", "Fiji", "Filipinas", "Finlandia", "Francia", "Gabon", "Gambia", "Georgia", "Ghana", "Granada", "Grecia", "Guatemala", "Guinea", "GuineaEcuatorial", "GuineaBissau", "Guyana", "Haiti", "Honduras", "Hungria", "India", "Indonesia", "Iran", "Iraq", "Irlanda", "Islandia", "IslasCook", "IslasMarshall", "IslasSalomon", "Israel", "Italia", "Jamaica", "Japon", "Jordania", "Kazajstan", "Kenya", "Kirguistan", "Kiribati", "Kuwait", "Lesotho", "Letonia", "Libano", "Liberia", "Libia", "Liechtenstein", "Lituania", "Luxemburgo", "Madagascar", "Malasia", "Malawi", "Maldivas", "Mali", "Malta", "Marruecos", "Mauricio", "Mauritania", "Mexico", "Micronesia", "Monaco", "Mongolia", "Montenegro", "Mozambique", "Myanmar", "Namibia", "Nauru", "Nepal", "Nicaragua", "", "Nigeria", "Niue", "Noruega", "NuevaZelandia", "Oman", "PaisesBajos", "Pakistan", "Palau", "Panama", "PapuaNuevaGuinea", "Paraguay", "Peru", "Polonia", "Portugal", "Qatar", "ReinoUnido", "Siria", "", "Corea (la)", "MacedoniadelNorte", "", "Moldova", "Congo", "Lao", "RepublicaDominicana", "Corea", "Tanzania", "Rumania", "Rwanda", "", "Samoa", "SanMarino", "", "SantaLucia", "", "SantoTomeyPrincipe", "Senegal", "Serbia", "Seychelles", "SierraLeona", "Singapur", "Somalia", "SriLanka", "Sudafrica", "Sudan", "", "Suecia", "Suiza", "Suriname", "Tailandia", "Tayikistan", "", "Togo", "Tonga", "Trinidady Tabago", "Tunez", "Turkmenistan", "Turquia", "Tuvalu", "Ucrania", "Uganda", "Uruguay", "Uzbekistan", "Vanuatu", "Venezuela", "VietNam", "Yemen", "Zambia", "Zimbabwe"];
var animales = ["Animales", "Abeja", "Abejaruco", "Abejorro", "aguila", "Albatros", "Alce", "Almeja", "Anguilaelectrica", "Anguilamorena", "Antilope", "Ardilla", "Armadillo", "Armiño", "Avedelparaiso", "Avestruz", "Avispa", "Babuino", "Ballenaazul", "Barracuda", "Bisonte", "Bufalo", "Buho", "Buitre", "Burro", "Caballo", "Cabra", "Cachalote", "Caiman", "Calamar", "Camaleon", "Camaron", "Camello", "Cangrejo", "Canguro", "Caracol", "Castor", "Casuario", "Cebra", "Cebu", "Cerdo", "Cerdo", "Chacal", "Chimpance", "Chinchilla", "Ciempies", "Ciervo", "Cigüeña", "Cisne", "Coati", "Cobaya", "Cocodrilo", "Codorniz", "Colibri", "Comadreja", "Conejo", "Coral", "Coyote", "Cucaracha", "Delfin", "DemoniodeTasmania", "Elefante", "Erizo", "Escarabajo", "Escorpion", "Faisan", "Flamenco", "Foca", "Gallina", "Gamba", "Ganso", "Garza", "GatO", "GatoBombay", "Gorila", "Gorrion", "Grulla", "Guacamayo", "Guepardo", "Halcon", "Hamster", "Hiena", "Hipopotamo", "Hormiga", "Huron", "Iguana", "Impala", "Jabali", "Jaguar", "Jirafa", "Kiwi", "Koala", "Lagarto", "Langosta", "Lechuza", "Lemur", "Leon", "Leonmarino", "Leopardo", "Libelula", "Liebre", "Lince", "Llama", "Lobo", "Loro", "Luciernaga", "Manati", "Mandril", "Mangosta", "Mantarraya", "Mapache", "Mariposa", "Mariquita", "Medusa", "Mono", "Morsa", "Mosca", "Mula", "Murcielago", "Musaraña", "Nutria", "Ocelote", "Orangutan", "Orca", "Ornitorrinco", "Oruga", "Oso", "Ostra", "Oveja", "Pantera", "Pato", "Pavo", "Pelicano", "Percebe", "Perezoso", "Perro", "Piraña", "Polilla", "Pollo", "Proteo", "Puercoespin", "Pulpo", "Puma", "Quetzal", "Rata", "Raton", "Raya", "Reno", "Rinoceronte", "Salamandra", "Saltamontes", "Sapo", "Serpiente", "Tejon", "Tiburon", "Tigre", "Topo", "Tortuga", "Tucan", "Urraca", "Vaca", "Yarara", "Zarigüeya", "Zorro"];
var hogar = ["Objetos de la casa", "Aireacondicionado", "Alfombra", "Antejardin", "atico", "Azotea", "Bajadadecama", "Balcon", "Baño", "Biblioteca", "Biombo", "Bodega", "Boveda", "Buzon", "Calefactor", "Celosia", "Cielo", "Cocina", "Comedor", "Cortina", "Chapa", "Chimenea", "Dormitorio", "Enchufe", "Entretecho", "Escalera", "Espejo", "Estacionamiento", "Estudio", "Estufa", "Guardapolvo", "Interruptor", "Jardin", "Manilla", "Mansarda", "Mesadecentro", "Muralla", "Librero", "Limpiapies", "Pared", "Pasillo", "Patio", "Persiana", "Picaporte", "Piso", "Puerta", "Porton", "Reja", "SaladeEstar", "Sillon", "Sofa", "Sotano", "Suelo", "Techo", "Terraza", "Umbral", "Ventana", "Ventanal", "Ventilador", "Velador"];
var profesiones = ["Profesiones", "Abogado", "Actor", "Agentedeviaje", "Arquitecto", "Astronomo", "Autor", "Barrendero", "Bibliotecario", "Bombero", "Carnicero", "Carpintero", "Cartero", "chofer", "Cientifico", "Cirujano", "Cocinero", "Contador", "Corredor", "Dentista", "Diseñador", "Doctor", "Electricista", "Enfermero", "Estilista", "Farmaceutico", "Florista", "Fontanero", "Fotografo", "Granjero", "Jardinero", "Juez", "Limpiadordevidrios", "Mecanico", "Mesero", "Modelo", "Oftalmologo", "Panadero", "Peluquero", "Periodista", "Pescador", "Piloto", "Pintor", "Plomero", "Policia", "Politico", "Profesor", "Psiquiatra", "Recepcionista", "Salvavidas", "Sastre", "Secretario", "Soldado", "Taxista", "Traductor", "Vendedor", "Veterinario"];
var personalidad = ["Caracteriticas personales", "Atento", "Atinado", "Bromista", "Cambiante", "Cobarde", "Conflictivo", "Constante", "Creativo", "Desatinado", "Desequilibrado", "Desordenado", "Desubicado", "Diplomatico", "Dominante", "Eficiente", "Egoista", "Equilibrado", "Estricto", "Estupido", "Exigente", "Firme", "Flojo", "Frivolo", "Generoso", "Grave", "Ignorante", "Impaciente", "Impredecible", "Impuntual", "Indulgente", "Ineficiente", "Insensato", "Inteligente", "Intolerante", "Luchador", "Olvidadizo", "Ordenado", "Paciente", "Pacifico", "Permisivo", "Predecible", "Puntual", "Pusilanime", "Rudo", "Sabio", "Sensato", "Serio", "Solidario", "Sumiso", "Tacaño", "Testarudo", "Tolerante", "Trabajador", "Transigente", "Ubicado", "Valiente", "Voluble"];
var deportes = ["Deportes", "Atletismo", "Badminton", "Baloncesto", "Beisbol", "Boxeo", "Buceo", "Ciclismo", "Equitacion", "Esgrima", "Esqui", "Esquiacuatico", "Futbol", "Gimnasiaartistica", "Gimnasiaritmica", "Golf", "Hockey", "Judo", "Montañismo", "Motociclismo", "Natacion", "Paracaidismo", "Parapente", "Patinaje", "Polo", "Remo", "Rugby", "Surf", "Taekwondo", "Tenis", "Tiroalblanco", "Tiroconarco", "Voleibol"];
var cuerpo = ["Cuerpo Humano", "antebrazo", "arterias", "axila", "bazo", "boca", "brazo", "cabeza", "cadera", "canilla", "ceja", "cerebro", "cintura", "codo", "columna", "corazon", "costilla", "craneo", "cuello", "dedo", "diente", "espalda", "esqueleto", "estomago", "femur", "fosanasal", "frente", "garganta", "higado", "hombro", "hueso", "lengua", "mano", "mejilla", "menton", "muela", "muñeca", "musculo", "muslo", "nariz", "nudillo", "ojo", "ombligo", "oreja", "palma", "pancreas", "parpado", "pecho", "pestaña", "pie", "piel", "pierna", "pulgar", "pulmon", "riñon", "rodilla", "rostro", "sangre", "talon", "tobillo", "traquea", "uña", "vejiga", "vello", "vena", "vertebra"];"antebrazo","arterias","axila","bazo","boca","brazo","cabeza","cadera","canilla","ceja","cerebro","cintura","codo","columna","corazon","costilla","craneo","cuello","dedo","diente","espalda","esqueleto","estomago","femur","fosanasal","frente","garganta","higado","hombro","hueso","lengua","mano","mejilla","menton","muela","muñeca","musculo","muslo","nariz","nudillo","ojo","ombligo","oreja","palma","pancreas","parpado","pecho","pestaña","pie","piel","pierna","pulgar","pulmon","riñon","rodilla","rostro","sangre","talon","tobillo","traquea","uña","vejiga","vello","vena","vertebra"

const categorias = [palabrasUsuario, masLargas, paises, animales, hogar, profesiones, personalidad, deportes, cuerpo];

function seleccionaCategoria() {
    // CHQUEAMOS QUE HAYAN PALABRAS DE USUARIO
    let sinPalabrasUsuario = 0;
    if (palabrasUsuario.length <= 1) {
        sinPalabrasUsuario = 1;
    }
    var idCategoria = Math.round(Math.random() * (categorias.length - 1 - sinPalabrasUsuario)) + sinPalabrasUsuario;

    return categorias[idCategoria];
}

function seleccionaPalabra(categoriaElegida) {
    var nroPalabras = cuentaPalabras(categoriaElegida);
    console.log("nro palabras" + nroPalabras);
    var idPalabra = Math.round(Math.random() * (nroPalabras - 2) + 2); // el valor minimo es 2 porque la primera palabra es el la categoria
    var palabra = categoriaElegida[idPalabra - 1];
    console.log("palabra: " + palabra);
    return palabra;
}


function cuentaPalabras(categoriaElegida) {
    return nroPalabras = categoriaElegida.length;
}

function cuentaLetras(palabra) {
    return nroLetras = palabra.length;
}



